# Site settings
title: uTrade Engineering
email: info@utradesolutions.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Engineering Blog of uTrade Solutions, a trading technology
  company with its development center based in Chandigarh, India.
baseurl: "/engg-blog/" # the subpath of your site, e.g. /blog/
url: "http://utrade.github.io" # the base hostname & protocol for your site
twitter_username: uTradeSolutions
github_username:  utrade

# Build settings
markdown: kramdown
